# Generated by Django 4.0 on 2021-12-09 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_itinerary_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flights.agent', verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='currency',
            field=models.CharField(max_length=7, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flights.airline', verbose_name='Aerolinea'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arrival_leg', to='flights.airport', verbose_name='Aeropuerto de llegada'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='departure_leg', to='flights.airport', verbose_name='Aeropuerto de salida'),
        ),
    ]
